# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: "Fetching raw data from external website"

on:
  push:
  schedule:
   - cron: "0 0 * * 3,6" # every Wednesday and Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Get the number of infecteds of nationwide and by-state from GitHub of Ministry of Health Malaysia
      run: |
        python -m fetch_data.fetch_all

    - name: Export the above results to GitHub repository
      env:
        GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git config user.email "$GIT_OWNER_EMAIL"
        git config user.name "drxyzw"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -a -m "Automatically updating raw market quote data"
          git remote rm origin
          git remote add origin https://drxyzw:$PUSH_TOKEN@github.com/drxyzw/crypto-dashboard.git
          git push origin HEAD:master
        else
          echo 'there is no change'
        fi
